### ISSUE TITLE
大佬  hanwckf 固件怎么更新smartdns

### ISSUE THREAD

**Issue by lalasou** [blioild/smartdns-scripts-for-padavan#1]
求指导

能不能更新下

**Comment by blioild** [comment]
> 求指导
> 
> 能不能更新下

把 smartdns 的源码 (tar.gz 格式) 放到 rt-n56u/trunk/user/smartdns 下，修改该目录下的 Makefile ，SRC_NAME 行适当修改。
我的仓库刚更新到 Release35 啦，自动编译完成后固件就可以直接用了。

**Comment by lalasou** [comment]
ok 谢谢
